table DimARBuckets
	lineageTag: b681efed-626a-4bb8-9042-75b3b8cd26b4

	column ARIndex
		dataType: int64
		formatString: 0
		lineageTag: b18ac330-6179-49bc-9a98-26e5cf41d78b
		summarizeBy: sum
		sourceColumn: ARIndex

		annotation SummarizationSetBy = Automatic

	column 'AR Buckets'
		dataType: string
		lineageTag: 8743c2ad-7501-4c60-ad53-74815049150c
		summarizeBy: none
		sourceColumn: AR Buckets
		sortByColumn: ARIndex

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition DimARBuckets-0db79c5d-f70a-4fa9-8702-9bc32b5e753d = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci4tKkrNK1HSUTJUitWJVjJU0FUwNgByjcBcYxDfDMQ3BvPNQHxLEN8EzI8pNTAwToWImCrFxgIA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"AR Buckets" = _t, ARIndex = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"AR Buckets", type text}, {"ARIndex", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

