table DimAgingCategory
	lineageTag: 00b3570a-b3d6-426d-8508-b6b6c0da75fc

	column AgingCategory
		dataType: string
		lineageTag: f6f6f73a-8c5e-4c28-9073-1c22b959970e
		summarizeBy: none
		sourceColumn: AgingCategory
		sortByColumn: AgingCategoryID

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column AgingCategoryID
		dataType: int64
		formatString: 0
		lineageTag: c8f45074-0e6e-4c82-be30-459c862d509b
		summarizeBy: none
		sourceColumn: AgingCategoryID

		annotation SummarizationSetBy = Automatic

	partition DimAgingCategory = m
		mode: import
		queryGroup: 'SharePoint Tables'
		source =
				let
				    Source = SharePoint.Files("https://vipsearchgroup.sharepoint.com/sites/SolutionsAdmin/", [ApiVersion = 15]),
				    #"SH Consulting Actual Hours - Working - 2025 xlsx_https://vipsearchgroup sharepoint com/sites/SolutionsAdmin/Shared Documents/Utilization Tracker/" = Source{[Name="SH Consulting Actual Hours - Working - 2025.xlsx",#"Folder Path"="https://vipsearchgroup.sharepoint.com/sites/SolutionsAdmin/Shared Documents/Utilization Tracker/"]}[Content],
				    #"Imported Excel Workbook" = Excel.Workbook(#"SH Consulting Actual Hours - Working - 2025 xlsx_https://vipsearchgroup sharepoint com/sites/SolutionsAdmin/Shared Documents/Utilization Tracker/"),
				    #"AR Data_Sheet" = #"Imported Excel Workbook"{[Item="AR Data",Kind="Sheet"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"AR Data_Sheet",{"Column1", "Column2"}),
				    #"Removed Top Rows" = Table.Skip(#"Removed Columns",2),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Other Columns" = Table.SelectColumns(#"Promoted Headers",{"Owner", "ClientName", "Total", "Curr", "31-60", "61-90", "91-120", "121-180", "181-360", "Over 360"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Other Columns", each ([ClientName] <> null and [ClientName] <> "")),
				    #"Added Custom" = Table.AddColumn(#"Filtered Rows", "Over 91", each [#"91-120"] + [#"121-180"] + [#"181-360"] + [Over 360]),
				    #"Removed Columns2" = Table.RemoveColumns(#"Added Custom",{"91-120", "121-180", "181-360", "Over 360"}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Columns2", {"ClientName", "Owner"}, "Attribute", "Value"),
				    #"Filtered Rows1" = Table.SelectRows(#"Unpivoted Other Columns", each ([Attribute] <> "Total")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows1",{{"Attribute", "AgingCategory"}, {"Value", "ARAmount"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"ARAmount", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Curr","Current",Replacer.ReplaceText,{"AgingCategory"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Replaced Value",{"AgingCategory"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns1"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "AgingCategoryID", 1, 1, Int64.Type)
				in
				    #"Added Index"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

