table DimManagingDirectorTotal
	lineageTag: 3021dea8-1f53-440a-a3ec-70f1b44cd13f

	measure ManagedTotal = SUM(DimManagingDirectorTotal[Amount])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 19de8257-c0a6-41e9-a2fa-86f52a15bafc

	column DealId
		dataType: int64
		formatString: 0
		lineageTag: 381a257c-83fe-42c8-89bf-a9b749471de8
		summarizeBy: count
		sourceColumn: DealId

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: double
		lineageTag: 3d4ae974-adfd-495e-bb73-2f6fc36b87d2
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Director
		dataType: string
		lineageTag: f8f18de5-1c24-493d-84ce-c9d88bf9b1b4
		summarizeBy: none
		sourceColumn: Director

		annotation SummarizationSetBy = Automatic

	partition DimManagingDirectorTotal-e2c7ec49-4162-4dc1-b2e5-26ce1d9bda32 = m
		mode: import
		queryGroup: 'HubSpot Tables'
		source =
				let
				    Source = FactHubSpotDeal,
				    #"Filtered Rows" = Table.SelectRows(Source, each ([DealStageName] = "Closed Won")),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","Matthew Edwards","Matt Edwards",Replacer.ReplaceText,{"Director"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Replaced Value",{"DealId", "Amount", "Director"})
				in
				    #"Removed Other Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

