table InvoiceBudget
	lineageTag: ec5dd389-3ce1-48cd-ac56-22d2d0253dea

	measure 'Invoice Budget Sum' = SUM(InvoiceBudget[Value])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d9ffb3ff-6354-49ae-b81d-dede5de876f4

	column Year
		dataType: dateTime
		formatString: Long Date
		lineageTag: fb0d0958-15b1-451e-98f5-876995b25056
		summarizeBy: none
		sourceColumn: Year

		variation Variation
			isDefault
			relationship: d27a8fc8-5499-4265-8096-fac34e0a2b2a
			defaultHierarchy: LocalDateTable_4edada56-4d5a-491b-9f31-5bb3937869fd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 6d59cb86-7132-4ee9-80c8-ae98f0a68bd8
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: b26c241a-b5fd-4e32-9449-b7e11137abf0
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 30358b55-9e65-4d6c-ac84-7539a38628dd
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	partition InvoiceBudget-650da7ba-6b25-4b56-ae6e-a0f1029940aa = m
		mode: import
		queryGroup: 'HubSpot Tables'
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://vipsearchgroup.sharepoint.com/sites/VIPPowerBI/Shared%20Documents/General/VIP%20Internal%20-%20(PB-2208-003)/Budgeted%20Sales%20Requirements.xlsx"), null, true),
				    InvoiceBucket_Sheet = Source{[Item="InvoiceBucket",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(InvoiceBucket_Sheet, [PromoteAllScalars=true]),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Promoted Headers", {"SalesRep"}, "Attribute", "Value"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Unpivoted Columns",{{"Attribute", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each Date.IsInCurrentYear([Attribute])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows",{{"Value", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Attribute", "Year"}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Renamed Columns", "SalesRep", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"SalesRep.1", "SalesRep.2"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Split Column by Delimiter",{{"SalesRep.1", "FirstName"}, {"SalesRep.2", "LastName"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

